title:
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
url: ""
twitter_username: bballport
github_username:  dblackrun

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
